name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
      # - run: echo ${{ toJson(github) }}
      # - name: Slack message
      #   run: |
      #     curl -X POST -H 'Content-type: application/json'
      #     --data '{"text":"New Release!! <${{
      #     github.event.repository.html_url }}|check it out!
      #     >"}' ${{ secrets.SLACK_WEBHOOK }}
